AllCops:
  NewCops: enable
  Exclude:
    - dist/build/**/*
    - dist/rubies/**/*

Bundler/GemFilename:
  Exclude:
    - examples/**/gems.rb
    - dist/**/gems.rb

Metrics/BlockLength:
  Exclude:
    - examples/**/*.rb

Metrics/MethodLength:
  Max: 17

Style/ZeroLengthPredicate:
  Exclude:
    - lib/wands/web_socket.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Exclude:
    - wands.gemspec


plugins:
  - rubocop-minitest
  - rubocop-rake
