AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Metrics/MethodLength:
  Max: 15

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Exclude:
    - wands.gemspec

require:
  - rubocop-minitest
  - rubocop-rake
