AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Bundler/GemFilename:
  Exclude:
    - examples/**/*.rb

Metrics/BlockLength:
  Exclude:
    - examples/**/*.rb

Metrics/MethodLength:
  Max: 17

Style/ZeroLengthPredicate:
  Exclude:
    - lib/wands/web_socket.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Exclude:
    - wands.gemspec

require:
  - rubocop-minitest
  - rubocop-rake
