AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 13

require:
  - rubocop-minitest
  - rubocop-rake
