name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build_ruby:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.4.1'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run the default task
        run: bundle exec rake

      - name: Build wasm
        run: bundle exec rake wasm:build

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Test in Node WASI
        run: npm test
