name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build_ruby:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.4.1'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run the default task
        run: bundle exec rake

      - name: Install WASM build dependencies
        run: |
          cd dist
          export BUNDLE_GEMFILE=$(pwd)/gems.rb
          bundle install

      - name: Cache Ruby WASM binary
        uses: actions/cache@v3
        with:
          path: dist/rubies/
          key: ruby-wasm-${{ runner.os }}-${{ matrix.ruby }}
          restore-keys: |
            ruby-wasm-${{ runner.os }}-

      - name: Show cached files
        run: |
          if [ -d dist/rubies ]; then
            ls -lh dist/rubies
          else
            echo "No cached rubies found."
          fi

      - name: Build wasm
        run: |
          cd dist
          export BUNDLE_GEMFILE=$(pwd)/gems.rb
          bundle exec rbwasm build --ruby-version 3.4 -o ruby+wands.wasm

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run:  |
          cd node_wasi_test
          npm install

      - name: Test in Node WASI
        run: |
          cd node_wasi_test
          npm test
